# Generated by Django 4.0.4 on 2022-05-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=50, unique=True)),
                ('voucher', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('billing_type', models.CharField(max_length=50)),
                ('plate_num', models.CharField(max_length=50)),
                ('overtime', models.DurationField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('parking_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingentry')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('parking_spot', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.client')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.paymentregister')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.client')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.paymentregister')),
            ],
        ),
        migrations.AddField(
            model_name='parkingentry',
            name='reservation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.reservation'),
        ),
    ]
