# Generated by Django 4.0.4 on 2022-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingentry',
            name='billing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parkingentry',
            name='overtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
