# Generated by Django 4.0.4 on 2022-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingentry_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingentry',
            name='billing_type',
            field=models.CharField(choices=[('ADH', 'AD_HOC'), ('VCR', 'VOUCHER'), ('SUB', 'SUBSCRIPTION')], default='ADH', max_length=12),
        ),
    ]
