# Generated by Django 4.0.4 on 2022-05-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingentry_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentregister',
            name='status',
            field=models.CharField(choices=[('P', 'PAID'), ('U', 'UNPAID')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='parkingentry',
            name='billing_type',
            field=models.CharField(choices=[('ADH', 'AD_HOC'), ('VCR', 'VOUCHER'), ('SUB', 'SUBSCRIPTION')], default='ADH', max_length=3),
        ),
    ]
