# Generated by Django 4.0.4 on 2022-05-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_paymentregister_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentregister',
            name='parking_entry_id',
            field=models.IntegerField(),
        ),
    ]
