# Generated by Django 4.0.4 on 2022-06-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_paymentregister_parking_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='voucher',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentregister',
            name='parking_entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
