# Generated by Django 4.0.4 on 2022-06-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_client_voucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='parking_spot',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
