# Generated by Django 4.0.4 on 2022-06-13 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_remove_subscription_parking_spot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='voucher',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
